/**
 * Comprehensive lists for target roles and prior exposure.
 * Tech and non-tech options for career roadmaps.
 */

export const TARGET_ROLES = [
  // Tech / Engineering
  "Frontend Engineer",
  "Backend Engineer",
  "Full Stack Developer",
  "Software Engineer",
  "Senior Software Engineer",
  "Staff Engineer",
  "Data Scientist",
  "Data Engineer",
  "Data Analyst",
  "Machine Learning Engineer",
  "AI Engineer",
  "DevOps Engineer",
  "Site Reliability Engineer",
  "Cloud Engineer",
  "Cloud Architect",
  "Security Engineer",
  "QA Engineer",
  "Test Engineer",
  "Mobile Developer (iOS)",
  "Mobile Developer (Android)",
  "Game Developer",
  "Blockchain Developer",
  "Embedded Systems Engineer",
  "Systems Engineer",
  "Database Administrator",
  "Network Engineer",
  // Product & Design
  "Product Manager",
  "Senior Product Manager",
  "Product Owner",
  "Product Designer",
  "UX Designer",
  "UI Designer",
  "UX Researcher",
  "UX Writer",
  "Interaction Designer",
  "Service Designer",
  "Technical Writer",
  "Documentation Engineer",
  // Business & Operations
  "Project Manager",
  "Program Manager",
  "Scrum Master",
  "Agile Coach",
  "Business Analyst",
  "Systems Analyst",
  "Financial Analyst",
  "Investment Analyst",
  "Management Consultant",
  "Strategy Consultant",
  "Operations Manager",
  "Supply Chain Manager",
  "Procurement Manager",
  // Marketing & Sales
  "Marketing Manager",
  "Digital Marketing Manager",
  "Content Marketing Manager",
  "SEO Specialist",
  "SEM Specialist",
  "Growth Manager",
  "Brand Manager",
  "Product Marketing Manager",
  "Sales Representative",
  "Sales Engineer",
  "Account Executive",
  "Account Manager",
  "Business Development Representative",
  "Customer Success Manager",
  "Partnership Manager",
  // Creative & Content
  "Content Writer",
  "Copywriter",
  "Content Strategist",
  "Social Media Manager",
  "Community Manager",
  "Graphic Designer",
  "Visual Designer",
  "Motion Designer",
  "Video Editor",
  "Photographer",
  "Illustrator",
  // HR & Recruiting
  "HR Manager",
  "HR Business Partner",
  "Recruiter",
  "Technical Recruiter",
  "Talent Acquisition Specialist",
  "Learning & Development Specialist",
  "Compensation Analyst",
  // Legal & Compliance
  "Legal Counsel",
  "Compliance Officer",
  "Privacy Officer",
  // Executive & Leadership
  "Engineering Manager",
  "Director of Engineering",
  "CTO",
  "VP of Product",
  "VP of Engineering",
  "CEO",
  "Founder",
  // Other
  "Support Engineer",
  "Solutions Architect",
  "Implementation Consultant",
  "Customer Support Specialist",
  "Executive Assistant",
] as const;

export const PRIOR_EXPOSURE_OPTIONS = [
  // Programming & Web
  "HTML",
  "CSS",
  "JavaScript",
  "TypeScript",
  "React",
  "Vue",
  "Angular",
  "Svelte",
  "Next.js",
  "Node.js",
  "Express",
  "Python",
  "Django",
  "Flask",
  "FastAPI",
  "Java",
  "Spring",
  "Kotlin",
  "Swift",
  "C#",
  ".NET",
  "Go",
  "Rust",
  "Ruby",
  "Rails",
  "PHP",
  "Laravel",
  "SQL",
  "PostgreSQL",
  "MySQL",
  "MongoDB",
  "Redis",
  "Git",
  "GitHub",
  "GitLab",
  "REST APIs",
  "GraphQL",
  "gRPC",
  "WebSockets",
  // Data & ML
  "Excel",
  "Google Sheets",
  "Data analysis",
  "Data visualization",
  "Pandas",
  "NumPy",
  "Machine learning",
  "Deep learning",
  "TensorFlow",
  "PyTorch",
  "Statistics",
  "SQL queries",
  // Cloud & DevOps
  "AWS",
  "Azure",
  "Google Cloud",
  "Docker",
  "Kubernetes",
  "Terraform",
  "CI/CD",
  "Linux",
  "Bash",
  "Server administration",
  // Design & Tools
  "Figma",
  "Adobe XD",
  "Sketch",
  "Adobe Photoshop",
  "Adobe Illustrator",
  "Adobe After Effects",
  "Wireframing",
  "Prototyping",
  "User research",
  "Usability testing",
  "Design systems",
  // Business & Soft Skills
  "Project management",
  "Agile",
  "Scrum",
  "Kanban",
  "Jira",
  "Confluence",
  "Writing",
  "Technical writing",
  "Public speaking",
  "Presentation skills",
  "Leadership",
  "Communication",
  "Negotiation",
  "Stakeholder management",
  "Budgeting",
  "Strategic planning",
  // Marketing
  "SEO",
  "Google Analytics",
  "Content creation",
  "Social media",
  "Email marketing",
  "Copywriting",
  // Other
  "None",
] as const;

/** Quick-add chips for target role (common options) */
export const ROLE_QUICK_ADD = [
  "Frontend Engineer",
  "Backend Engineer",
  "Full Stack Developer",
  "Data Scientist",
  "Product Manager",
  "UX Designer",
  "DevOps Engineer",
] as const;

/** Quick-add chips for prior exposure (common options) */
export const PRIOR_EXPOSURE_QUICK_ADD = [
  "JavaScript",
  "React",
  "Python",
  "HTML",
  "CSS",
  "Git",
  "SQL",
  "Excel",
] as const;

/**
 * Prior skills chips for onboarding / settings (freeform strings stored in profiles).
 * Values are human-readable labels that also go into the LLM prompt.
 */
export const PROFILE_PRIOR_EXPOSURE = [
  ...PRIOR_EXPOSURE_QUICK_ADD.map((label) => ({ value: label, label })),
  { value: "TypeScript", label: "TypeScript" },
  { value: "SQL", label: "SQL" },
  { value: "REST APIs", label: "REST APIs" },
  { value: "Figma", label: "Figma" },
  { value: "Writing", label: "Writing" },
  { value: "SEO", label: "SEO" },
  { value: "Project management", label: "Project management" },
  { value: "None", label: "None" },
] as const;

export type ProfilePriorExposureValue =
  (typeof PROFILE_PRIOR_EXPOSURE)[number]["value"];

export type TargetRole = (typeof TARGET_ROLES)[number];
export type PriorExposure = (typeof PRIOR_EXPOSURE_OPTIONS)[number];
